"""Initial migration - v1.4 schema

Revision ID: 64ed1241be8c
Revises: 
Create Date: 2026-03-10 16:48:31.754000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ed1241be8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source_platform_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_location', ['city', 'district'], unique=False)
        batch_op.create_index('idx_jobs_salary', ['salary_min', 'salary_max'], unique=False)
        batch_op.create_index('idx_jobs_title', ['title'], unique=False)
        batch_op.create_index('idx_jobs_unique', ['platform', 'source_platform_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_salary_min'), ['salary_min'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('target_jobs', sa.JSON(), nullable=True),
    sa.Column('expected_city', sa.String(length=100), nullable=True),
    sa.Column('expected_salary_min', sa.Integer(), nullable=True),
    sa.Column('expected_salary_max', sa.Integer(), nullable=True),
    sa.Column('resume_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_industry', ['industry'], unique=False)
        batch_op.create_index('idx_users_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_vector', sa.JSON(), nullable=True),
    sa.Column('match_details', sa.JSON(), nullable=True),
    sa.Column('industry_score', sa.Float(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('salary_score', sa.Float(), nullable=True),
    sa.Column('location_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('tools_score', sa.Float(), nullable=True),
    sa.Column('is_viewed', sa.Integer(), nullable=True),
    sa.Column('is_applied', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('idx_matches_user_score', ['user_id', 'match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_match_score'), ['match_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('platform_status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('hr_reply', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_applications_status', ['status'], unique=False)
        batch_op.create_index('idx_applications_user_job', ['user_id', 'job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_applied_at'), ['applied_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applied_at'))
        batch_op.drop_index('idx_applications_user_job')
        batch_op.drop_index('idx_applications_status')

    op.drop_table('applications')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_matches_match_score'))
        batch_op.drop_index(batch_op.f('ix_matches_job_id'))
        batch_op.drop_index(batch_op.f('ix_matches_id'))
        batch_op.drop_index(batch_op.f('ix_matches_created_at'))
        batch_op.drop_index('idx_matches_user_score')

    op.drop_table('matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index('idx_users_name')
        batch_op.drop_index('idx_users_industry')

    op.drop_table('users')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_salary_min'))
        batch_op.drop_index(batch_op.f('ix_jobs_industry'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_city'))
        batch_op.drop_index('idx_jobs_unique')
        batch_op.drop_index('idx_jobs_title')
        batch_op.drop_index('idx_jobs_salary')
        batch_op.drop_index('idx_jobs_location')

    op.drop_table('jobs')
    # ### end Alembic commands ###
